# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edda2b36408a9aab7ddc7509a9d219a6bbf848a230de3f4fb91813de11d9243a3995ab61be5b0dae53c362426a28f683db4192762805d702ffa097f1ef03c155

test:
  secret_key_base: 8d867139111851ae1e113fc9f7f53d6f72107ca878122dddfb13d8adebf7dd1c20d1f641354dfb10b3d5d6eb7a4fa288b921b6946407d7fe8b66d27153ab2d45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
